In [ ]:
def operation(a, b):
    print("The sum of the numbers is:", a + b)
    print("The product of the numbers is:", a * b)
    print("The difference of the numbers is:", a - b)
    print("The division of the numbers is:")
    if b == 0:
        print("Undefined")
    else:
        print(a / b)

print("Please enter the first number:")
a = int(input())
print("Please enter the second number:")
b = int(input())

operation(a, b)


Please enter the first number:
4
Please enter the second number:
7
The sum of the numbers is: 11
The product of the numbers is: 28
The difference of the numbers is: -3
The division of the numbers is:
0.5714285714285714


In [ ]:

a = str(input("Enter your name\n"))
b = int(input("Enter your age\n"))
print("Hello",a,"you will turn",b+1,"next year!")

Enter your name
sanjay
Enter your age
19
Hello sanjay you will turn 20 next year!


In [ ]:
a = int(input("Enter a number:\n"))
if a%2==0:
  print("The number is even")
else:
  print("The number is odd")

Enter a number:
4
The number is even


In [ ]:
a= int(input("Enter the number for which you want to find the multiplication for:\n"))
for i in range(11):
  print(a,"x",i,"=",a*i)


Enter the number for which you want to find the multiplication for:
4
4 x 0 = 0
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40


In [ ]:
print("We are goint to print numbers that are divisible by 7 in the range 1 to 100")
for i in range(101):
  if i%7==0:
    print(i)
  else:
    continue

We are goint to print numbers that are divisible by 7 in the range 1 to 100
0
7
14
21
28
35
42
49
56
63
70
77
84
91
98


In [ ]:


num = int(input("Enter a number: "))

factorial = 1

for i in range(1, num + 1):
    factorial *= i   # multiply factorial by i at each step

print("The factorial of", num, "is", factorial)

Enter a number: 4
The factorial of 4 is 24


In [ ]:


numbers = []
for i in range(10):
    num = int(input(f"Enter number {i+1}: "))
    numbers.append(num)


print("\nEven numbers:")
for n in numbers:
    if n % 2 == 0:
        print(n, end=" ")


print("\nOdd numbers:")
for n in numbers:
    if n % 2 != 0:
        print(n, end=" ")

56
total = sum(numbers)
average = total / len(numbers)

print("\n\nSum of numbers:", total)
print("Average of numbers:", average)

Enter number 1: 1
Enter number 2: 2
Enter number 3: 3
Enter number 4: 4
Enter number 5: 4
Enter number 6: 5
Enter number 7: 6
Enter number 8: 7
Enter number 9: 7
Enter number 10: 8

Even numbers:
2 4 4 6 8 
Odd numbers:
1 3 5 7 7 

Sum of numbers: 47
Average of numbers: 4.7


In [ ]:
key = 17
count = 0

Num = int(input("Guess a number between 1 to 100:\n"))

while Num != key:
    print("Take one more guess\n")
    count += 1
    Num = int(input("Guess again:\n"))

print("Finally!! You got it in", count + 1, "attempts")


Guess a number between 1 to 100:
6
Take one more guess

Guess again:
17
Finally!! You got it in 2 attempt(s).




---

##  Print
- **Purpose:** Display output on the screen.
```python
print("Hello, World!")
```
Output:
```
Hello, World!
```

---

##  Variables
- **Purpose:** Store values for later use.
```python
x = 10
name = "Sanjay"
print(x, name)
```
Output:
```
10 Sanjay
```

---

##  Operators
- **Arithmetic:** `+`, `-`, `*`, `/`, `%` (modulus), `**` (power), `//` (floor division)
```python
a = 5
b = 2
print(a + b)   # 7
print(a - b)   # 3
print(a * b)   # 10
print(a / b)   # 2.5
print(a % b)   # 1
print(a ** b)  # 25
print(a // b)  # 2
```

- **Comparison:** `==`, `!=`, `<`, `>`, `<=`, `>=`
```python
print(5 == 5)   # True
print(5 != 3)   # True
print(5 > 3)    # True
```

- **Logical:** `and`, `or`, `not`
```python
print(True and False)  # False
print(True or False)   # True
print(not True)        # False
```

---

##  Input
- **Purpose:** Take user input.
```python
num = int(input("Enter a number: "))
print("You entered:", num)
```

---

##  Conditionals
- **Purpose:** Make decisions.
```python
age = int(input("Enter your age: "))
if age >= 18:
    print("You are an adult.")
else:
    print("You are a minor.")
```

---

##  Loops
- **For loop:** Repeat a block for a fixed range.
```python
for i in range(5):
    print("Iteration:", i)
```

- **While loop:** Repeat until a condition is false.
```python
count = 0
while count < 5:
    print("Count:", count)
    count += 1
```

---




In [ ]:
def operations(a, b):
    return a + b, a - b, a * b, a / b


print(operations(10, 2))  # (12, 8, 20, 5.0)

(12, 8, 20, 5.0)


In [ ]:
fruits = ["apple", "banana", "mango", "orange", "grape"]
fruits.append("pineapple")
fruits.append("papaya")
fruits.remove("banana")
print("Final list:", fruits)

Final list: ['apple', 'mango', 'orange', 'grape', 'pineapple', 'papaya']


In [ ]:
cities = ("Chennai", "Delhi", "Mumbai", "Kolkata", "Bengaluru")
for city in cities:
    print(city)

Chennai
Delhi
Mumbai
Kolkata
Bengaluru


In [ ]:
def is_palindrome(s):
    return s == s[::-1]

print(is_palindrome("madam"))
print(is_palindrome("hello"))

True
False


In [ ]:
def stats(numbers):
    return max(numbers), min(numbers), sum(numbers)/len(numbers)

nums = [12, 45, 23, 67, 89, 34, 22, 90, 11, 56]
print(stats(nums))  # (90, 11, 44.9)

(90, 11, 44.9)


In [ ]:
library = {}

def add_book(book_name):
    library[book_name] = True

def borrow_book(book_name):
    if library.get(book_name):
        library[book_name] = False
        print(f"You borrowed '{book_name}'")
    else:
        print(f"'{book_name}' is not available")

def return_book(book_name):
    if book_name in library:
        library[book_name] = True
        print(f"You returned '{book_name}'")
    else:
        print(f"'{book_name}' does not belong to this library")

def print_available_books():
    print("\nAvailable books:")
    for book, available in library.items():
        if available:
            print(book)

# Example usage
add_book("Python Basics")
add_book("Data Science 101")
add_book("Machine Learning")

borrow_book("Python Basics")
return_book("Python Basics")
print_available_books()

You borrowed 'Python Basics'
You returned 'Python Basics'

Available books:
Python Basics
Data Science 101
Machine Learning




---

# 📘 Python Basics Notebook

## 1. Functions
**Notes:**  
- Functions are reusable blocks of code.  
- Defined using `def`.  
- Can take parameters and return values.  

```python
# Example: Function to add two numbers
def add_numbers(a, b):
    return a + b

print(add_numbers(5, 3))  # Output: 8
```

---

## 2. Lists
**Notes:**  
- Ordered, mutable collections.  
- Defined with square brackets `[]`.  
- Support indexing, slicing, and methods like `.append()`, `.remove()`.  

```python
fruits = ["apple", "banana", "mango"]
fruits.append("orange")   # Add item
fruits.remove("banana")   # Remove item
print("Fruits list:", fruits)
print("First fruit:", fruits[0])
```

---

## 3. Tuples
**Notes:**  
- Ordered, immutable collections.  
- Defined with parentheses `()`.  
- Useful for fixed data.  

```python
cities = ("Chennai", "Delhi", "Mumbai")
for city in cities:
    print("City:", city)
```

---

## 4. Sets
**Notes:**  
- Unordered collections of unique elements.  
- Defined with curly braces `{}`.  
- Useful for removing duplicates and set operations.  

```python
numbers = {1, 2, 3, 3, 4}
print("Set:", numbers)  # Duplicates removed

# Set operations
a = {1, 2, 3}
b = {3, 4, 5}
print("Union:", a | b)
print("Intersection:", a & b)
print("Difference:", a - b)
```

---

## 5. Dictionaries
**Notes:**  
- Store key-value pairs.  
- Defined with curly braces `{}`.  
- Keys must be unique.  

```python
student_marks = {"Sanjay": 85, "Priya": 92, "Arun": 78}
print("Marks dictionary:", student_marks)
print("Priya's marks:", student_marks["Priya"])

# Add new key-value pair
student_marks["Meena"] = 95
print("Updated dictionary:", student_marks)

# Loop through dictionary
for name, marks in student_marks.items():
    print(name, "scored", marks)
```

---




In [ ]:
import numpy as np

arr = np.arange(1, 21)
print("Array:", arr)
print("Even numbers:", arr[arr % 2 == 0])

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Even numbers: [ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
matrix = np.full((3, 3), 7)
print(matrix)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
rand_arr = np.random.rand(10)
print(rand_arr)

[0.34273659 0.7497461  0.62844732 0.23305874 0.92812061 0.03639481
 0.712373   0.8836027  0.67926653 0.75470854]


In [ ]:
arr = np.arange(1, 17).reshape(4, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
arr = np.random.randint(1, 10, (5, 5))
print("Array:\n", arr)

print("Row sums:", arr.sum(axis=1))
print("Column means:", arr.mean(axis=0))

Array:
 [[6 9 9 2 2]
 [4 2 8 3 2]
 [8 5 2 6 3]
 [9 3 9 6 1]
 [4 7 8 2 1]]
Row sums: [28 19 24 28 22]
Column means: [6.2 5.2 7.2 3.8 1.8]


In [ ]:
arr = np.random.randint(1, 101, (10, 10))
print("Matrix:\n", arr)

# Find max element & position
max_val = arr.max()
pos = np.unravel_index(arr.argmax(), arr.shape)
print("Max value:", max_val, "at position:", pos)

# Replace numbers > 50 with 0
arr[arr > 50] = 0
print("Modified matrix:\n", arr)

Matrix:
 [[ 79  52  82  70  33  78  71  97  50 100]
 [ 49  65  84  15  32  78  34  78   5 100]
 [ 71  70  28  25  23  28  15  15  66  11]
 [ 90  63  68  66  23   4  32  81  47  14]
 [ 66   1  17  69  68  99  52  74  97  37]
 [ 76  36  25  98  62  24  28   3  55  36]
 [ 94  10  72  72  46  92   5  90  93   1]
 [ 66  97  27  28  10  87  70  14  47  11]
 [ 99  65  42  28   8  96   1  10  28  23]
 [ 48  98  38  31  63  40  51  71  17  27]]
Max value: 100 at position: (np.int64(0), np.int64(9))
Modified matrix:
 [[ 0  0  0  0 33  0  0  0 50  0]
 [49  0  0 15 32  0 34  0  5  0]
 [ 0  0 28 25 23 28 15 15  0 11]
 [ 0  0  0  0 23  4 32  0 47 14]
 [ 0  1 17  0  0  0  0  0  0 37]
 [ 0 36 25  0  0 24 28  3  0 36]
 [ 0 10  0  0 46  0  5  0  0  1]
 [ 0  0 27 28 10  0  0 14 47 11]
 [ 0  0 42 28  8  0  1 10 28 23]
 [48  0 38 31  0 40  0  0 17 27]]




---

# 📘 NumPy Arrays Basics

## 1. Array Creation
**Notes:**
- Arrays are created using `np.array()` or helper functions like `np.arange()`, `np.zeros()`, `np.ones()`, `np.full()`, `np.random.rand()`.
- Arrays can be 1D, 2D, or higher dimensions.

```python
import numpy as np

# 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D array:", arr1)

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", arr2)

# Range of numbers
arr3 = np.arange(1, 11)  # numbers 1 to 10
print("Range array:", arr3)

# Zeros and ones
zeros = np.zeros((2, 3))
ones = np.ones((2, 3))
print("Zeros:\n", zeros)
print("Ones:\n", ones)

# Random numbers
rand_arr = np.random.rand(3, 3)
print("Random array:\n", rand_arr)
```

---

## 2. Indexing
**Notes:**
- Access elements using square brackets `[]`.
- Works like Python lists but supports multi-dimensional indexing.

```python
arr = np.array([10, 20, 30, 40, 50])
print("First element:", arr[0])
print("Last element:", arr[-1])

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Element at row 0, col 1:", matrix[0, 1])  # 2
print("Element at row 1, col 2:", matrix[1, 2])  # 6
```

---

## 3. Slicing
**Notes:**
- Extract subarrays using `start:end:step`.
- Works in multiple dimensions.

```python
arr = np.arange(1, 11)  # [1,2,...,10]
print("Slice 2 to 6:", arr[2:7])       # [3,4,5,6,7]
print("Every second element:", arr[::2])  # [1,3,5,7,9]

matrix = np.arange(1, 10).reshape(3, 3)
print("Matrix:\n", matrix)
print("First row:", matrix[0, :])
print("First column:", matrix[:, 0])
print("Submatrix:\n", matrix[0:2, 1:3])
```

---

## 4. Operations
**Notes:**
- Arrays support element-wise arithmetic and broadcasting.
- Common operations: `+`, `-`, `*`, `/`, `**`.
- Aggregate functions: `.sum()`, `.mean()`, `.max()`, `.min()`.

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise operations
print("Addition:", arr1 + arr2)
print("Multiplication:", arr1 * arr2)

# Scalar operations
print("Multiply by 10:", arr1 * 10)

# Aggregate functions
print("Sum:", arr1.sum())
print("Mean:", arr1.mean())
print("Max:", arr1.max())
print("Min:", arr1.min())
```

---


